[[projects]]
name="Project One"
tags=["foobar"]
ticket_prefix="TKT-"

[[projects]]
name="Project Two"
ticket_prefix="TWO-"
tags=["evilcorp"]
epochs=[
    { from = 2026-01-01, rate = { rate = 20000, currency = "GBP" }},
]

[[projects]]
name="Acme"
tags=["acme"]
ticket_prefix="TKT-"
