name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    if: github.event_name == 'release'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/pttlogger
            asset_name: pttlogger-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/pttlogger.exe
            asset_name: pttlogger-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/pttlogger
            asset_name: pttlogger-macos

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked
